#!/bin/bash

if grep -Fxq "// @begin" $1
then
ROOTPATH=$(python -c "import os.path; print os.path.relpath('$3', '$1/..')")
DEST=$(echo $1 | sed "s/$(echo $2 | sed -e 's/[]\/()$*.^|[]/\\&/g')/$(echo $3 | sed -e 's/[\/&]/\\&/g')/g" | sed 's/\(.*\.\)h/\1html/')
echo $DEST
mkdir -p "$(dirname "$DEST")"
sed -n '/^\/\/ /s,// ,,p' $1 | awk '/@begin/,/@end/' | sed '1d;$d' | markdown | cat $3/detail/header.htm - $3/detail/tail.htm | sed "s/ROOTPATH/$(echo $ROOTPATH | sed -e 's/[\/&]/\\&/g')/g" > $DEST
fi